wicket:
  configuration-type: development
  wicketstuff:
    htmlcompressor:
      enabled: false
      features:
        compressCSS: false
  devutils:
    statelesschecker:
      enabled: true
    interceptor:
      enable-live-sessions-page: true
    diskstorebrowser:
      enabled: true
  wicketsource:
    enabled: true