wicket:
  configuration-type: development
  wicketstuff:
    htmlcompressor:
      enabled: false
      features:
        compressCSS: false
    annotationscan:
      enabled: true
  devutils:
    interceptor:
      enable-live-sessions-page: true
    diskstorebrowser:
      enabled: true