wicket:
  stuff:
    datastore:
      hazelcast:
        enabled: false
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
        - +*.map
    csrf:
      accepted-origins:
        - localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  compression:
    enabled: true
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
