wicket:
  configuration-type: development
  wicketstuff:
    htmlcompressor:
      features:
        compressCSS: true
    annotationscan:
      enabled: true

  devutils:
    diskstorebrowser:
      enabled: true